spring:
  application:
    name: gateway-sys
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
          #鼠标焦点查询微服务
        - id: uxdl_system
          uri: lb://system
          predicates:
            - Path=/admin/virtual_data,/admin/virtual_data/**,/admin/materials,/admin/materials/**,/admin/categorys/**,/admin/categorys,/admin/tags,/admin/tags/**,/admin/users/**,/admin/users,/admin/admins,/admin/admins/**,/admin/ads,/admin/ads/**,/admin/statistics/core/,/admin/statistics/core/**
          filters:
            - StripPrefix=1
          #认证微服务
        - id: uxdl_system-auth
          uri: lb://system-auth
          predicates:
            - Path=/backendoauth/**




  redis:
    host: localhost
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true