spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
          #认证微服务
        - id: oauth_user
          uri: lb://user-auth
          predicates:
            - Path=/oauth/**
          #user微服务
        - id: uxdl_tbuser
          uri: lb://tbuser
          predicates:
            - Path=/tbuser/**,/users/**,/usercenter/**
          #material微服务
        - id: uxdl_material
          uri: lb://material
          predicates:
            - Path=/materials/**,/num/**,/search/**,/ids,/ids/**



  redis:
    host: localhost
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true