server:
  port: 9500
spring:
  application:
    name: system-auth
  redis:
    host: localhost
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.9.143.69:3306/uxdl?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root123!
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: uxdl_system
  clientSecret: uxdl_system
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/uxdl_system.jks
    secret: uxdl_system
    alias: uxdl_system
    password: uxdl_system